### ISSUE TITLE
Merge with Proton-GE itself?

### ISSUE THREAD

**Issue by italoghost** [cammoore1/DAI-proton-ge-custom#3]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
First of all, thank you for your fork! I gave up on playing this the first time as I couldn't play with my controller. However, I wanted to know if it is possible to submit a PR to include these patches on Proton-GE itself. Is there any blocks that prevent it been added there?

## Justification [optional] 
Keeping it on Proton-GE would be better, as it would centralize patches for all games.

## Risks [optional]
N/A.

## References [optional] 
N/A.

**Comment by cammoore1** [comment]
I'll probably do a pull request soon. I didn't do it initially because I didn't know for sure if the workaround would mess up any other games (it probably would have initially which is likely why the EA App broke v1.0.2). It is a loooot less likely to mess up a game now with v1.0.4 since it checks for the thread / process name before doing anything. 

Only reason I have been putting off the pull request at the moment was because I was waiting to see if there were any other language requests, but I'm pretty sure that the thread / process names are consistent across versions (although several French users reported the game not working and then one reported it suddenly working so not sure what the deal is there).

**Comment by italoghost** [comment]
As a brazilian, I will test the PT-BR version and return to you.

**Comment by italoghost** [comment]
Closing as it was merged on Proton-GE
